export const selectedColumnsToShow = ref([
  "title",
  "cost_code",
  "description",
  "quantity",
  "unit_cost",
  "unit",
  "total_price",
]);

export const selectedColumnsToPrint = ref([
  "title",
  "cost_code",
  "description",
  "quantity",
  "unit_cost",
  "unit",
  "total_price",
]);

export const columnsTitle = [
  { value: "title", label: "Title" },
  { value: "description", label: "Description" },
  { value: "unit_cost", label: "Unit Cost" },
  { value: "quantity", label: "Quantity" },
  { value: "unit", label: "Unit" },
  { value: "cost_code", label: "Cost Code" },
  { value: "builder_cost", label: "Builder Cost" },
  { value: "markup", label: "Markup" },
  { value: "margin", label: "Margin" },
  { value: "total_price", label: "Total Price" },
  { value: "cost_type", label: "Cost Type" },
  { value: "group_amount", label: "Group Amount" },
  { value: "notes", label: "Notes" },
  { value: "profit", label: "Profit" },
  //   { value: "total_markup", label: "Total Markup" },
  //   { value: "markup_amount", label: "Markup Amount" },
];

export const getColumnData = ref({
  // cost_code: "cost_code",
  title: "title",
  unit: "unit",
  description: "description",
  cost_type: "cost_type",
  mark_as: "mark_as",
  quantity: "quantity",
  unit_cost: "unit_cost",
  total_price: "total_price",
  builder_cost: "builder_cost",
  markup: "markup",
  margin: "margin",
  status: "status",
  group_amount: "group_amount",
  profit: "profit",
  internal_notes: "internal_notes",
  //   markup_amount: "markup_amount",
  //   total_markup: "total_markup",
});

export const getColumnName = ref({
  cost_code: "Cost Code",
  title: "Title",
  unit: "Unit",
  description: "Description",
  cost_type: "Cost Type",
  mark_as: "Mark As",
  quantity: "Qty",
  unit_cost: "Unit Cost",
  builder_cost: "Builder Cost",
  markup: "Markup",
  markup_amount: "Markup Amount",
  status: "Status",
  margin: "Margin",
  total_price: "Total Price",
  group_amount: "Group Price",
  TotalCost: "Total Cost",
  total_markup: "Total Markup",
  profit: "Profit",
  notes: "Internal Notes",
  state: "State",
});
