export const getStatusColor = {
  onHold: "warning",
  open: "info",
  sold: "success",
  lost: "danger",
};

export const getLeadStatusName = {
  onHold: "On Hold",
  open: "Open",
  sold: "Sold",
  lost: "Lost",
};

export const getProposalStatusColor = {
  pending: "info",
  approved: "success",
  approve: "success",
  review: "warning",
  disapprove: "danger",
};

export const getProposalStatusName = {
  pending: "Pending",
  approved: "Approved",
  approve: "Approved",
  review: "Require Review",
  disapprove: "Disapproved",
};

export const getProposalTypeColor = {
  proposal: "primary",
  change_order: "warning",
  draft: "light",
};

export const getProposalTypeName = {
  proposal: "Proposal",
  change_order: "Change Order",
  draft: "Draft",
};

export const activityTypes = [
  { value: "call", label: "Phone Call" },
  { value: "email", label: "Email" },
  { value: "followup", label: "Follow Up" },
  { value: "visit", label: "Site Visit" },
  { value: "form", label: "Website Form" },
];

export const leadStatus = ref([
  { value: "open", label: "Open" },
  { value: "inProgress", label: "In Progress" },
  { value: "onHold", label: "On Hold" },
  { value: "pending", label: "Pending" },
  { value: "lost", label: "Lost" },
  { value: "sold", label: "sold" },
  { value: "noOpportunity", label: "No Opportunity" },
]);

export const generalUnits = [
  {
    label: "Square Foot",
    // value: "sq_ft",
    value: "Sq Ft",
    category: "area",
  },
  {
    label: "Square Meter",
    // value: "sq_m",
    value: "Sq M",
    category: "area",
  },
  {
    label: "Acre",
    // value: "acre",
    value: "Acre",
    category: "area",
  },
  {
    label: "Hectare",
    // value: "ha",
    value: "Ha",
    category: "area",
  },
  {
    label: "Square Yard",
    // value: "sq_yd",
    value: "Sq Yd",
    category: "area",
  },
  {
    label: "Square Inch",
    // value: "sq_in",
    value: "Sq inch",
    category: "area",
  },
  {
    label: "Meter",
    // value: "m",
    value: "M",
    category: "length",
  },
  {
    label: "Centimeter",
    // value: "cm",
    value: "CM",
    category: "length",
  },
  {
    label: "Millimeter",
    // value: "mm",
    value: "MM",
    category: "length",
  },
  {
    label: "Foot",
    // value: "ft",
    value: "Ft",
    category: "length",
  },
  {
    label: "Inch",
    // value: "in",
    value: "Inch",
    category: "length",
  },
  {
    label: "Yard",
    // value: "yd",
    value: "Yard",
    category: "length",
  },
  {
    label: "Cubic Meter",
    // value: "m3",
    value: "M3",
    category: "volume",
  },
  {
    label: "Cubic Foot",
    // value: "ft3",
    value: "Ft3",
    category: "volume",
  },
  {
    label: "Cubic Yard",
    // value: "yd3",
    value: "Yd3",
    category: "volume",
  },
  {
    label: "Liter",
    // value: "L",
    value: "L",
    category: "volume",
  },
  {
    label: "Gallon",
    // value: "gal",
    value: "Gal",
    category: "volume",
  },
  {
    label: "Kilogram",
    // value: "kg",
    value: "kg",
    category: "weight",
  },
  {
    label: "Gram",
    // value: "g",
    value: "g",
    category: "weight",
  },
  {
    label: "Pound",
    // value: "lb",
    value: "lb",
    category: "weight",
  },
  {
    label: "Ounce",
    // value: "oz",
    value: "oz",
    category: "weight",
  },
  {
    label: "Ton",
    // value: "ton",
    value: "Ton",
    category: "weight",
  },
  {
    label: "Metric Ton",
    // value: "tonne",
    value: "Tonne",
    category: "weight",
  },
  {
    label: "Bag (Cement)",
    // value: "bag",
    value: "Bag",
    category: "materials",
  },
  {
    label: "Cubic Yard (Concrete)",
    // value: "yd3_concrete",
    value: "Yd3 Concrete",
    category: "materials",
  },
  {
    label: "Sheet (Drywall)",
    // value: "sheet",
    value: "Sheet",
    category: "materials",
  },
  {
    label: "Board Foot (Lumber)",
    // value: "board_ft",
    value: "board Ft",
    category: "materials",
  },
  {
    label: "Linear Foot",
    // value: "linear_ft",
    value: "Linear Ft",
    category: "materials",
  },
  {
    label: "Square Foot (Flooring)",
    // value: "sq_ft_flooring",
    value: "Sq Ft Flooring",
    category: "materials",
  },
  {
    label: "Roll (Insulation)",
    // value: "roll",
    value: "Roll",
    category: "materials",
  },
  {
    label: "Tile (Floor/Wall)",
    // value: "tile",
    value: "Tile",
    category: "materials",
  },
  {
    label: "Brick",
    // value: "brick",
    value: "Brick",
    category: "materials",
  },
  {
    label: "Block (Concrete)",
    // value: "block",
    value: "Block",
    category: "materials",
  },
  {
    label: "Pallet (Bricks/Blocks)",
    // value: "pallet",
    value: "Pallet",
    category: "materials",
  },
  {
    label: "Hour",
    // value: "hr",
    value: "Hr",
    category: "time",
  },
  {
    label: "Day",
    // value: "day",
    value: "Day",
    category: "time",
  },
  {
    label: "Week",
    // value: "week",
    value: "Week",
    category: "time",
  },
  {
    label: "Month",
    // value: "month",
    value: "month",
    category: "time",
  },
  {
    label: "Year",
    // value: "year",
    value: "year",
    category: "time",
  },
  {
    label: "Watt",
    // value: "W",
    value: "W",
    category: "power",
  },
  {
    label: "Kilowatt",
    // value: "kW",
    value: "kW",
    category: "power",
  },
  {
    label: "Horsepower",
    // value: "hp",
    value: "hp",
    category: "power",
  },
  {
    label: "BTU (Heating/Cooling)",
    // value: "btu",
    value: "btu",
    category: "energy",
  },
  {
    label: "Therm (Gas)",
    // value: "therm",
    value: "therm",
    category: "energy",
  },
  {
    label: "Pascal",
    // value: "Pa",
    value: "Pa",
    category: "pressure",
  },
  {
    label: "Kilopascal",
    // value: "kPa",
    value: "kPa",
    category: "pressure",
  },
  {
    label: "PSI (Pounds per Square Inch)",
    // value: "psi",
    value: "psi",
    category: "pressure",
  },
  {
    label: "Degree Celsius",
    // value: "°C",
    value: "°C",
    category: "temperature",
  },
  {
    label: "Degree Fahrenheit",
    // value: "°F",
    value: "°F",
    category: "temperature",
  },
];

export const getUnitsLabel = ref({
  square_foot: "Sq Ft",
  square_meter: "Sq M",
  acre: "Acre",
  hectare: "Ha",
  square_yard: "Sq Yd",
  square_inch: "Sq inch",
  meter: "M",
  centimeter: "CM",
  millimeter: "MM",
  foot: "Ft",
  inch: "Inch",
  yard: "Yard",
  cubic_meter: "M3",
  cubic_foot: "Ft3",
  cubic_yard: "Yd3",
  liter: "L",
  gallon: "Gal",
  kilogram: "kg",
  gram: "g",
  pound: "lb",
  ounce: "oz",
  ton: "Ton",
  metric_ton: "Tonne",
  "bag_(cement)": "Bag",
  "cubic_yard_(concrete)": "Yd3 Concrete",
  "sheet_(drywall)": "Sheet",
  "board_foot_(lumber)": "board Ft",
  linear_foot: "Linear Ft",
  "square_foot_(flooring)": "Sq Ft Flooring",
  "roll_(insulation)": "Roll",
  "tile_(floor/wall)": "Tile",
  brick: "Brick",
  "block_(concrete)": "Block",
  "pallet_(bricks/blocks)": "Pallet",
  hour: "Hr",
  day: "Day",
  week: "Week",
  month: "month",
  year: "year",
  watt: "W",
  kilowatt: "kW",
  horsepower: "hp",
  "btu_(heating/cooling)": "btu",
  "therm_(gas)": "therm",
  pascal: "Pa",
  kilopascal: "kPa",
  "psi_(pounds_per_square_inch)": "psi",
  degree_celsius: "°C",
  degree_fahrenheit: "°F",
});
