export const costItems = ref([
  {
    id: "12347",
    title: "Electrical Wiring",
    cost_code: "040100",
    cost_type: "Material",
    unit_cost: 20.0,
    quantity: 500,
    unit: "meters",
    total_cost: 10000.0,
    price: 750.0,
    markup: 15,
    markup_type: "percentage",
    markup_value: 1500.0,
    markup_amount: 3000.0,
    unit_price: 50.0,
    tax_rate: 7.5,
    client_price: 12000.9,
    total_price: 9000.0,
    builder_cost: 825.0,
    group_price: 78987.0,
    grand_total: 12325.0,
    total_markup: 9874567.0,
    mark_as: "catalogue_item",
    description: "Electrical wiring and related materials.",
    internal_notes: "Include wiring for backup generator.",
    created_by: "user125",
    created_date: "2024-12-22T12:00:00Z",
    updated_by: "user125",
    updated_date: "2024-12-22T13:00:00Z",
    approved_by: "manager458",
    approval_date: "2024-12-22T18:00:00Z",
    status: "pending",
    category: "Electrical",
    tags: ["wiring", "electrical", "materials"],
    attachments: [],
    visibility: {
      admin: true,
      internal_only: false,
      shared_with_client: false,
    },
    front_end_elements: {
      highlighted: false,
      background_color: "#f0f0f0",
      font_color: "#000000",
      display_order: 3,
      editable: true,
    },
  },
  {
    id: "56789",
    title: "Plumbing Fixtures",
    cost_code: "050200",
    cost_type: "Labor",
    unit_cost: 45.0,
    quantity: 200,
    unit: "hours",
    total_cost: 9000.0,
    price: 1500.0,
    markup: 20,
    markup_type: "percentage",
    markup_value: 1800.0,
    markup_amount: 3600.0,
    unit_price: 75.0,
    tax_rate: 8.0,
    client_price: 12000.9,
    total_price: 10800.0,
    builder_cost: 950.0,
    group_price: 67890.0,
    grand_total: 13200.0,
    total_markup: 1234567.0,
    mark_as: "custom_item",
    description: "Installation of plumbing fixtures.",
    internal_notes: "Check water pressure before installation.",
    created_by: "user456",
    created_date: "2024-11-30T09:00:00Z",
    updated_by: "user456",
    updated_date: "2024-12-01T10:00:00Z",
    approved_by: "manager123",
    approval_date: "2024-12-01T15:00:00Z",
    status: "approved",
    category: "Plumbing",
    tags: ["plumbing", "fixtures", "labor"],
    attachments: [],
    visibility: {
      admin: true,
      internal_only: true,
      shared_with_client: false,
    },
    front_end_elements: {
      highlighted: true,
      background_color: "#ffffff",
      font_color: "#333333",
      display_order: 1,
      editable: false,
    },
  },
  {
    id: "90123",
    title: "HVAC Installation",
    cost_code: "070300",
    cost_type: "Service",
    unit_cost: 75.0,
    quantity: 50,
    unit: "units",
    total_cost: 3750.0,
    client_price: 12000.9,
    price: 850.0,
    markup: 10,
    markup_type: "fixed",
    markup_value: 850.0,
    markup_amount: 1700.0,
    unit_price: 95.0,
    tax_rate: 6.5,
    total_price: 4200.0,
    builder_cost: 1025.0,
    group_price: 56789.0,
    grand_total: 15500.0,
    total_markup: 654321.0,
    mark_as: "service_item",
    description: "HVAC system installation and setup.",
    internal_notes: "Ensure proper duct sealing.",
    created_by: "user789",
    created_date: "2024-12-10T14:00:00Z",
    updated_by: "user789",
    updated_date: "2024-12-15T11:30:00Z",
    approved_by: "manager567",
    approval_date: "2024-12-16T09:00:00Z",
    status: "completed",
    category: "HVAC",
    tags: ["HVAC", "installation", "service"],
    attachments: [],
    visibility: {
      admin: true,
      internal_only: false,
      shared_with_client: true,
    },
    front_end_elements: {
      highlighted: true,
      background_color: "#e6e6e6",
      font_color: "#111111",
      display_order: 2,
      editable: true,
    },
  },
  {
    id: "34567",
    title: "Roofing Materials",
    cost_code: "080500",
    cost_type: "Material",
    unit_cost: 30.0,
    quantity: 1000,
    unit: "sheets",
    total_cost: 30000.0,
    client_price: 12000.9,
    price: 1200.0,
    markup: 25,
    markup_type: "percentage",
    markup_value: 3000.0,
    markup_amount: 7500.0,
    unit_price: 90.0,
    tax_rate: 9.0,
    total_price: 32700.0,
    builder_cost: 1125.0,
    group_price: 43210.0,
    grand_total: 37500.0,
    total_markup: 98765.0,
    mark_as: "material_item",
    description: "High-quality roofing materials.",
    internal_notes: "Ensure weather-resistant properties.",
    created_by: "user321",
    created_date: "2024-12-05T08:00:00Z",
    updated_by: "user321",
    updated_date: "2024-12-06T12:00:00Z",
    approved_by: "manager789",
    approval_date: "2024-12-07T14:00:00Z",
    status: "pending",
    category: "Roofing",
    tags: ["roofing", "materials", "construction"],
    attachments: [],
    visibility: {
      admin: false,
      internal_only: true,
      shared_with_client: true,
    },
    front_end_elements: {
      highlighted: false,
      background_color: "#dddddd",
      font_color: "#444444",
      display_order: 4,
      editable: false,
    },
  },
]);

export const getColumnName = ref({
  ItemNumber: "No#",
  Title: "Title",
  Unit: "Cost Code",
  Description: "Description",
  CostType: "Cost Type",
  MarkAs: "Mark As",
  Quantity: "Quantity",
  UnitCost: "Unit Cost",
  BuilderCost: "Builder Cost",
  Markup: "Markup",
  MarkupAmount: "Markup Amount",
  UnitPrice: "Unit Price",
  Price: "Price",
  TotalPrice: "Total Price",
  GroupPrice: "Group Price",
  TotalCost: "Total Cost",
  TotalMarkup: "Total Markup",
  ClientPrice: "Client Price",
  Profit: "Profit",
  Notes: "Internal Notes",
});

export const getColumnData = ref({
  ItemNumber: "id",
  Title: "title",
  Unit: "cost_code",
  Description: "description",
  CostType: "cost_type",
  MarkAs: "mark_as",
  Quantity: "quantity",
  UnitCost: "unit_cost",
  BuilderCost: "builder_cost",
  Markup: "markup",
  MarkupAmount: "markup_amount",
  UnitPrice: "unit_price",
  Price: "price",
  TotalPrice: "total_price",
  GroupPrice: "group_price",
  TotalCost: "total_cost",
  TotalMarkup: "total_markup",
  ClientPrice: "client_price",
  Profit: "profit",
  Notes: "internal_notes",
});
