export const routerLinks = ref([
  {
    title: "Dashboard",
    icon: "lnir lnir-bar-chart",
    class: "single-link",
    route: "/sidebar/dashboard",
    linkType: "single",
  },
  {
    title: "Jobs & Leads",
    icon: "lnir lnir-library",
    collapseId: "estimates",
    class: "collapse-wrap",
    headerIcon: "lnir lnir-library",
    headerTitle: "Jobs & Leads",
    linkType: "collapse",
    children: [
      {
        title: "Lead Opportunity",
        icon: "lnir lnir-cloud-search",
        class: "is-submenu",
        route: "/sidebar/dashboard/leads",
        activeClass: "leads",
      },
      {
        title: "All Jobs",
        icon: "lnir lnir-suitcase",
        class: "is-submenu",
        route: "/sidebar/dashboard/jobs",
        activeClass: "projects",
      },
      {
        title: "Jobs Manager",
        icon: "lnir lnir-appointment",
        class: "is-submenu",
        route: "/sidebar/dashboard/manage-projects",
        activeClass: "manage-projects",
      },
      {
        title: "Workers Chart",
        icon: "lnir lnir-calendar",
        class: "is-submenu",
        route: "/sidebar/dashboard/workers-tasks",
        activeClass: "workers-tasks",
      },
      {
        title: "Lead Proposals",
        icon: "lnir lnir-add-files",
        class: "is-submenu",
        route: "/sidebar/dashboard/proposals",
      },
      {
        title: "Completed Jobs",
        icon: "lnir lnir-list",
        class: "is-submenu",
        route: "/sidebar/dashboard/completed-projects",
        activeClass: "pre-construction",
      },
    ],
  },
  // {
  //   title: "Leads & Jobs",
  //   icon: "lnir lnir-list-alt-1",
  //   collapseId: "Projects",
  //   class: "collapse-wrap",
  //   headerIcon: "lnir lnir-list-alt-1",
  //   headerTitle: "Leads & Jobs",
  //   linkType: "collapse",
  //   children: [
  //     {
  //       title: "All Jobs",
  //       icon: "lnir lnir-list-alt",
  //       class: "is-submenu",
  //       route: "/sidebar/dashboard/projects",
  //       activeClass: "projects",
  //     },
  //     {
  //       title: "Manage Projects",
  //       icon: "lnir lnir-appointment",
  //       class: "is-submenu",
  //       route: "/sidebar/dashboard/manage-projects",
  //       activeClass: "manage-projects",
  //     },
  //     {
  //       title: "Workers Chart",
  //       icon: "lnir lnir-calendar",
  //       class: "is-submenu",
  //       route: "/sidebar/dashboard/workers-tasks",
  //       activeClass: "workers-tasks",
  //     },
  //     {
  //       title: "Completed Projects",
  //       icon: "lnir lnir-list",
  //       class: "is-submenu",
  //       route: "/sidebar/dashboard/completed-projects",
  //       activeClass: "pre-construction",
  //     },
  //   ],
  // },
  {
    title: "Finance",
    icon: "lnir lnir-bank",
    collapseId: "payments",
    class: "collapse-wrap",
    headerIcon: "lnir lnir-bank",
    userIds: [
      "f6c283ec-9499-4983-997c-0456362e6650",
      "73462666-c7f0-41eb-b978-24f5ffe7a539",
    ],
    linkType: "collapse",
    headerTitle: "Finance",
    children: [
      {
        title: "Create Payment",
        icon: "lnir lnir-paypal",
        class: "is-submenu",
        route: "/sidebar/dashboard/create-payment",
        activeClass: "projects",
      },
      {
        title: "All Payments",
        icon: "lnir lnir-invest-monitor",
        class: "is-submenu",
        route: "/sidebar/dashboard/received-payments",
        activeClass: "received-payments",
      },
      // {
      //   title: "Approved Payments",
      //   icon: "lnir lnir-diagnosis-alt",
      //   class: "is-submenu",
      //   route: "/sidebar/dashboard/approved-payments",
      //   activeClass: "approved-payments",
      // },
      {
        title: "Succeeded Payments",
        icon: "lnir lnir-diagnosis-alt",
        class: "is-submenu",
        route: "/sidebar/dashboard/succeeded-payments",
        activeClass: "succeeded-payments",
      },
    ],
  },
  {
    title: "System Users",
    icon: "lnir lnir-users",
    collapseId: "users",
    class: "collapse-wrap",
    headerIcon: "lnir lnir-users",
    headerTitle: "System Users",
    linkType: "collapse",
    children: [
      {
        title: "Clients",
        icon: "lnir lnir-user-alt-2",
        class: "is-submenu",
        route: "/sidebar/dashboard/clients",
      },
      {
        title: "Managers",
        icon: "lnir lnir-user-alt-1",
        class: "is-submenu",
        route: "/sidebar/dashboard/managers",
      },
      {
        title: "Contractors",
        icon: "lnir lnir-user-alt",
        class: "is-submenu",
        route: "/sidebar/dashboard/contractors",
      },
      {
        title: "Sub Contractors",
        icon: "lnir lnir-user",
        class: "is-submenu",
        route: "/sidebar/dashboard/subcontractors",
      },
      {
        title: "Workers",
        icon: "lnir lnir-users",
        class: "is-submenu",
        route: "/sidebar/dashboard/workers",
      },
    ],
  },
  {
    title: "Company Settings",
    icon: "lnir lnir-cogs",
    collapseId: "setting",
    class: "collapse-wrap",
    headerIcon: "lnir lnir-cogs",
    headerTitle: "Company Settings",
    linkType: "collapse",
    children: [
      {
        title: "Settings",
        icon: "lnir lnir-cog",
        class: "is-submenu",
        route: "/sidebar/dashboard/company-settings",
      },
      {
        title: "Templates & Catalogs",
        icon: "lnir lnir-files",
        class: "is-submenu",
        route: "/sidebar/dashboard/proposal-templates",
      },
      // {
      //   title: "Files",
      //   icon: "lnir lnir-add-files",
      //   class: "is-submenu",
      //   route: "/sidebar/files-permission",
      // },
    ],
  },
  {
    title: "Profile",
    icon: "lnir lnir-user-alt-2",
    class: "single-link",
    route: "/sidebar/dashboard/profile",
    linkType: "single",
  },
]);

export const workerRouterLinks = ref([
  {
    title: "My Tasks",
    icon: "lnir lnir-list-alt",
    class: "single-link",
    route: "/sidebar/worker/tasks",
    linkType: "single",
  },
  {
    title: "Tasks Calendar",
    icon: "lnir lnir-calender-alt-1",
    class: "single-link",
    route: "/sidebar/worker/calendar",
    linkType: "single",
  },
  {
    title: "Profile",
    icon: "lnir lnir-user-alt-2",
    class: "single-link",
    route: "/sidebar/worker/profile",
    linkType: "single",
  },
]);
export const contractorRouterLinks = ref([
  {
    title: "My Projects",
    icon: "lnir lnir-list-alt",
    class: "single-link",
    route: "/sidebar/contractor/projects",
    linkType: "single",
  },
  {
    title: "Projects Calendar",
    icon: "lnir lnir-calender-alt-1",
    class: "single-link",
    route: "/sidebar/contractor/calendar",
    linkType: "single",
  },
  {
    title: "Profile",
    icon: "lnir lnir-user-alt-2",
    class: "single-link",
    route: "/sidebar/contractor/profile",
    linkType: "single",
  },
]);

export const managerRouterLinks = ref([
  {
    title: "My Projects",
    icon: "lnir lnir-list-alt",
    class: "single-link",
    route: "/sidebar/manager/projects",
    linkType: "single",
  },
  {
    title: "Projects Calendar",
    icon: "lnir lnir-calender-alt-1",
    class: "single-link",
    route: "/sidebar/manager/calendar",
    linkType: "single",
  },
  {
    title: "Profile",
    icon: "lnir lnir-user-alt-2",
    class: "single-link",
    route: "/sidebar/manager/profile",
    linkType: "single",
  },
]);

export const clientRouterLinks = ref([
  {
    title: "My Projects",
    icon: "lnir lnir-list-alt",
    class: "single-link",
    route: "/sidebar/client/projects",
    linkType: "single",
  },
  {
    title: "Profile",
    icon: "lnir lnir-user-alt-2",
    class: "single-link",
    route: "/sidebar/client/profile",
    linkType: "single",
  },
]);
