export const routerLinks = ref([
  {
    title: "Dashboard",
    icon: "lnir lnir-bar-chart",
    class: "single-link",
    route: "/sidebar/dashboard",
    linkType: "single",
    tabKey: "dashboard",
  },
  {
    title: "Jobs & Leads",
    icon: "lnir lnir-library",
    collapseId: "estimates",
    class: "collapse-wrap",
    headerIcon: "lnir lnir-library",
    headerTitle: "Jobs & Leads",
    linkType: "collapse",
    tabKey: "jobs_and_leads",
    children: [
      {
        title: "Lead Opportunity",
        icon: "lnir lnir-cloud-search",
        class: "is-submenu",
        route: "/sidebar/dashboard/leads",
        activeClass: "leads",
        tabKey: "jal_lead_opportunity",
      },
      {
        title: "All Jobs",
        icon: "lnir lnir-suitcase",
        class: "is-submenu",
        route: "/sidebar/dashboard/jobs",
        activeClass: "projects",
        tabKey: "jal_all_jobs",
      },
      {
        title: "Jobs Manager",
        icon: "lnir lnir-appointment",
        class: "is-submenu",
        route: "/sidebar/dashboard/manage-projects",
        activeClass: "manage-projects",
        tabKey: "jal_jobs_manager",
      },
      {
        title: "Workers Chart",
        icon: "lnir lnir-calendar",
        class: "is-submenu",
        route: "/sidebar/dashboard/workers-tasks",
        activeClass: "workers-tasks",
        tabKey: "jal_workers_chart",
      },
      {
        title: "Lead Proposals",
        icon: "lnir lnir-add-files",
        class: "is-submenu",
        route: "/sidebar/dashboard/proposals",
        tabKey: "jal_lead_proposals",
      },
      {
        title: "Completed Jobs",
        icon: "lnir lnir-list",
        class: "is-submenu",
        route: "/sidebar/dashboard/completed-projects",
        activeClass: "pre-construction",
        tabKey: "jal_completed_jobs",
      },
    ],
  },
  {
    title: "Finance",
    icon: "lnir lnir-bank",
    collapseId: "payments",
    class: "collapse-wrap",
    headerIcon: "lnir lnir-bank",
    linkType: "collapse",
    headerTitle: "Finance",
    tabKey: "finance",
    children: [
      {
        title: "Create Payment",
        icon: "lnir lnir-paypal",
        class: "is-submenu",
        route: "/sidebar/dashboard/create-payment",
        activeClass: "projects",
        tabKey: "fi_create_payments",
      },
      {
        title: "All Payments",
        icon: "lnir lnir-invest-monitor",
        class: "is-submenu",
        route: "/sidebar/dashboard/received-payments",
        activeClass: "received-payments",
        tabKey: "fi_all_payments",
      },
      // {
      //   title: "Approved Payments",
      //   icon: "lnir lnir-diagnosis-alt",
      //   class: "is-submenu",
      //   route: "/sidebar/dashboard/approved-payments",
      //   activeClass: "approved-payments",
      // },
      {
        title: "Succeeded Payments",
        icon: "lnir lnir-diagnosis-alt",
        class: "is-submenu",
        route: "/sidebar/dashboard/succeeded-payments",
        activeClass: "succeeded-payments",
        tabKey: "fi_succeeded_payments",
      },
    ],
  },
  {
    title: "System Users",
    icon: "lnir lnir-users",
    collapseId: "users",
    class: "collapse-wrap",
    headerIcon: "lnir lnir-users",
    headerTitle: "System Users",
    linkType: "collapse",
    tabKey: "system_users",
    children: [
      {
        title: "Clients",
        icon: "lnir lnir-user-alt-2",
        class: "is-submenu",
        route: "/sidebar/dashboard/clients",
        tabKey: "su_clients",
      },
      {
        title: "Managers",
        icon: "lnir lnir-user-alt-1",
        class: "is-submenu",
        route: "/sidebar/dashboard/managers",
        tabKey: "su_managers",
      },
      {
        title: "Contractors",
        icon: "lnir lnir-user-alt",
        class: "is-submenu",
        route: "/sidebar/dashboard/contractors",
        tabKey: "su_contractors",
      },
      {
        title: "Sub Contractors",
        icon: "lnir lnir-user",
        class: "is-submenu",
        route: "/sidebar/dashboard/subcontractors",
        tabKey: "su_subcontractors",
      },
      {
        title: "Workers",
        icon: "lnir lnir-users",
        class: "is-submenu",
        route: "/sidebar/dashboard/workers",
        tabKey: "su_workers",
      },
    ],
  },
  {
    title: "Company Settings",
    icon: "lnir lnir-cogs",
    collapseId: "setting",
    class: "collapse-wrap",
    headerIcon: "lnir lnir-cogs",
    headerTitle: "Company Settings",
    linkType: "collapse",
    tabKey: "company_settings",
    children: [
      {
        title: "Settings",
        icon: "lnir lnir-cog",
        class: "is-submenu",
        route: "/sidebar/dashboard/company-settings",
        tabKey: "cs_settings",
      },
      {
        title: "Templates & Catalogs",
        icon: "lnir lnir-files",
        class: "is-submenu",
        route: "/sidebar/dashboard/proposal-templates",
        tabKey: "cs_templates_and_catalogs",
      },
      // {
      //   title: "Files",
      //   icon: "lnir lnir-add-files",
      //   class: "is-submenu",
      //   route: "/sidebar/files-permission",
      // },
    ],
  },
  {
    title: "Profile",
    icon: "lnir lnir-user-alt-2",
    class: "single-link",
    route: "/sidebar/dashboard/profile",
    linkType: "single",
    tabKey: "profile",
  },
]);

export const workerRouterLinks = ref([
  {
    title: "My Tasks",
    icon: "lnir lnir-list-alt",
    class: "single-link",
    route: "/sidebar/worker/tasks",
    linkType: "single",
  },
  {
    title: "Tasks Calendar",
    icon: "lnir lnir-calender-alt-1",
    class: "single-link",
    route: "/sidebar/worker/calendar",
    linkType: "single",
  },
  {
    title: "Profile",
    icon: "lnir lnir-user-alt-2",
    class: "single-link",
    route: "/sidebar/worker/profile",
    linkType: "single",
  },
]);
export const contractorRouterLinks = ref([
  {
    title: "My Projects",
    icon: "lnir lnir-list-alt",
    class: "single-link",
    route: "/sidebar/contractor/projects",
    linkType: "single",
  },
  {
    title: "Projects Calendar",
    icon: "lnir lnir-calender-alt-1",
    class: "single-link",
    route: "/sidebar/contractor/calendar",
    linkType: "single",
  },
  {
    title: "Profile",
    icon: "lnir lnir-user-alt-2",
    class: "single-link",
    route: "/sidebar/contractor/profile",
    linkType: "single",
  },
]);

export const managerRouterLinks = ref([
  {
    title: "My Projects",
    icon: "lnir lnir-list-alt",
    class: "single-link",
    route: "/sidebar/manager/projects",
    linkType: "single",
  },
  {
    title: "Projects Calendar",
    icon: "lnir lnir-calender-alt-1",
    class: "single-link",
    route: "/sidebar/manager/calendar",
    linkType: "single",
  },
  {
    title: "Profile",
    icon: "lnir lnir-user-alt-2",
    class: "single-link",
    route: "/sidebar/manager/profile",
    linkType: "single",
  },
]);

export const clientRouterLinks = ref([
  {
    title: "My Projects",
    icon: "lnir lnir-list-alt",
    class: "single-link",
    route: "/sidebar/client/projects",
    linkType: "single",
  },
  {
    title: "Profile",
    icon: "lnir lnir-user-alt-2",
    class: "single-link",
    route: "/sidebar/client/profile",
    linkType: "single",
  },
]);
